# Generated by Django 4.2.25 on 2025-12-05 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="bedrooms",
        ),
        migrations.RemoveField(
            model_name="property",
            name="living_area",
        ),
        migrations.RemoveField(
            model_name="property",
            name="plot_area",
        ),
        migrations.RemoveField(
            model_name="property",
            name="price",
        ),
        migrations.RemoveField(
            model_name="property",
            name="price_per_sqm",
        ),
        migrations.RemoveField(
            model_name="property",
            name="roi",
        ),
        migrations.RemoveField(
            model_name="property",
            name="total_area",
        ),
        migrations.AddField(
            model_name="property",
            name="bedrooms_max",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Bedrooms to"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="bedrooms_min",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="0 = Studio",
                null=True,
                verbose_name="Bedrooms from",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="living_area_max",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Living area m² to",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="living_area_min",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Living area m² from",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="plot_area_max",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Plot area m² to",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="plot_area_min",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Plot area m² from",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="price_max",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Price $ to",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="price_min",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Price $ from",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="price_per_sqm_max",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Price per m² to",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="price_per_sqm_min",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Price per m² from",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="roi_max",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="ROI % to",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="roi_min",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="ROI % from",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="total_area_max",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Total area m² to",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="total_area_min",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Total area m² from",
            ),
        ),
    ]
