# Generated by Django 4.2.25 on 2025-12-07 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "properties",
            "0002_remove_property_bedrooms_remove_property_living_area_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="address",
            field=models.CharField(
                blank=True,
                help_text="For Google Maps autocomplete",
                max_length=500,
                verbose_name="Address",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=7,
                max_digits=10,
                null=True,
                verbose_name="Latitude",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=7,
                max_digits=10,
                null=True,
                verbose_name="Longitude",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="show_on_map",
            field=models.BooleanField(
                default=False, verbose_name="Show on homepage map"
            ),
        ),
    ]
