# Generated by Django 4.2.25 on 2025-12-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0003_property_address_property_latitude_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(unique=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 🌊",
                        max_length=10,
                        verbose_name="Icon emoji",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feature",
                "verbose_name_plural": "Features",
                "ordering": ["name"],
            },
        ),
        migrations.RemoveField(
            model_name="property",
            name="status",
        ),
        migrations.AddField(
            model_name="property",
            name="construction_status",
            field=models.CharField(
                choices=[
                    ("not_started", "Not Started"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("on_hold", "On Hold"),
                ],
                default="in_progress",
                max_length=20,
                verbose_name="Construction",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="ownership_type",
            field=models.CharField(
                choices=[("freehold", "Freehold"), ("leasehold", "Leasehold")],
                default="leasehold",
                max_length=20,
                verbose_name="Land Ownership",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="sale_status",
            field=models.CharField(
                choices=[
                    ("presale", "Pre-sale"),
                    ("selling", "Selling"),
                    ("soldout", "Sold Out"),
                ],
                default="selling",
                max_length=20,
                verbose_name="Sale Status",
            ),
        ),
        migrations.AddField(
            model_name="propertytype",
            name="icon",
            field=models.CharField(
                blank=True,
                help_text="e.g. 🏢",
                max_length=10,
                verbose_name="Icon emoji",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="features",
            field=models.ManyToManyField(
                blank=True, to="properties.feature", verbose_name="Features"
            ),
        ),
    ]
