# Generated by Django 4.2.25 on 2025-12-23 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0004_feature_remove_property_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="launch_date",
            field=models.CharField(
                blank=True,
                help_text="e.g. Q2 2028",
                max_length=50,
                verbose_name="Launch Date",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="total_units",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Total number of units in complex",
                null=True,
                verbose_name="Total Units",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="views",
            field=models.TextField(
                blank=True,
                help_text="Pool, Courtyard, Green Landscape - each on new line or comma separated",
                verbose_name="Views",
            ),
        ),
        migrations.CreateModel(
            name="PropertyUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Unit Type")),
                (
                    "total_area",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Total Area m²",
                    ),
                ),
                (
                    "living_area",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Living Area m²",
                    ),
                ),
                (
                    "outdoor_type",
                    models.CharField(blank=True, max_length=50, verbose_name="Outdoor"),
                ),
                (
                    "price_from",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Price From $",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="properties.property",
                        verbose_name="Property",
                    ),
                ),
            ],
            options={
                "verbose_name": "Property Unit",
                "verbose_name_plural": "Property Units",
                "ordering": ["order", "price_from"],
            },
        ),
    ]
