# Generated by Django 4.2.25 on 2025-12-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0005_property_launch_date_property_total_units_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="views",
        ),
        migrations.AddField(
            model_name="property",
            name="is_complex",
            field=models.BooleanField(
                default=False,
                help_text="Check if this is a complex with multiple unit types",
                verbose_name="Complex (multiple units)",
            ),
        ),
    ]
