# Generated by Django 4.2.25 on 2025-12-08 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CodeSnippet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. Google Analytics, Yandex Metrika",
                        max_length=100,
                        verbose_name="Name",
                    ),
                ),
                (
                    "code",
                    models.TextField(
                        help_text="Full script/meta tag with <script> or <meta>",
                        verbose_name="Code",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("head_start", "Head - Start (before styles)"),
                            ("head_end", "Head - End (after styles)"),
                            ("body_start", "Body - Start (after <body>)"),
                            ("body_end", "Body - End (before </body>)"),
                        ],
                        default="head_end",
                        max_length=20,
                        verbose_name="Location",
                    ),
                ),
                (
                    "load_type",
                    models.CharField(
                        choices=[
                            ("sync", "Sync (blocking)"),
                            ("async", "Async (non-blocking)"),
                            ("defer", "Defer (after DOM ready)"),
                        ],
                        default="async",
                        help_text="For scripts only. Async recommended for analytics.",
                        max_length=10,
                        verbose_name="Load type",
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Lower = loads first",
                        verbose_name="Priority",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "show_on_all",
                    models.BooleanField(default=True, verbose_name="Show on all pages"),
                ),
                (
                    "pages",
                    models.TextField(
                        blank=True,
                        help_text="URL paths, one per line. e.g. /about/",
                        verbose_name="Specific pages",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
            ],
            options={
                "verbose_name": "Code Snippet",
                "verbose_name_plural": "Code Snippets",
                "ordering": ["location", "priority"],
            },
        ),
    ]
